import { env } from "cloudflare:workers";
import { Heart, MapPin, CalendarDays, Gift, Music2 } from "lucide-react";
export const dynamic = "force-dynamic";
export type InviteContent={bride:string;groom:string;greeting:string;date:string;time:string;venue:string;address:string;mapsUrl:string;story:string;bankName:string;accountNumber:string;accountHolder:string;heroImage:string;coupleImage:string;gallery:string[]};
export const defaults:InviteContent={bride:"Charine",groom:"Jeivan",greeting:"Tuhan membuat segala sesuatu indah pada waktunya.",date:"2026-12-12",time:"14:00 WITA",venue:"Gereja & Aula Pernikahan",address:"Manado, Sulawesi Utara",mapsUrl:"https://maps.google.com",story:"Dengan penuh sukacita, kami mengundang Bapak/Ibu/Saudara/i untuk hadir dan menjadi bagian dari hari bahagia kami.",bankName:"Bank Mandiri",accountNumber:"0000 0000 0000",accountHolder:"Jeivan S. Momongan",heroImage:"",coupleImage:"",gallery:[]};
async function loadContent():Promise<InviteContent>{try{const row=await env.DB.prepare("SELECT content FROM invitation_content WHERE id = 1").first<{content:string}>();return row?.content?{...defaults,...JSON.parse(row.content)}:defaults}catch{return defaults}}
const photo=(src:string,n:string)=>src||`https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=${n}&q=85`;
export default async function Home({searchParams}:{searchParams:Promise<{to?:string}>}){const c=await loadContent();const q=await searchParams;const guest=(q.to||"Bapak/Ibu/Saudara/i").slice(0,80);const d=new Date(`${c.date}T00:00:00`);const fd=new Intl.DateTimeFormat("id-ID",{weekday:"long",day:"numeric",month:"long",year:"numeric"}).format(d);return <main>
<section id="home" className="hero" style={{backgroundImage:`linear-gradient(180deg,rgba(15,22,18,.18),rgba(15,22,18,.72)),url(${photo(c.heroImage,"1800")})`}}><nav><a href="#home" className="brand">J <span>&</span> C</a><div><a href="#acara">Acara</a><a href="#cerita">Cerita</a><a href="#galeri">Galeri</a><a href="#hadiah">Hadiah</a></div></nav><div className="hero-copy"><p className="eyebrow">The Wedding of</p><h1>{c.groom} <i>&</i> {c.bride}</h1><p className="hero-date">{fd}</p><div className="guest-box"><span>Kepada Yth.</span><strong>{guest}</strong><small>Mohon maaf apabila ada kesalahan penulisan nama atau gelar</small></div><a className="pill" href="#acara">Buka Undangan</a></div><div className="scroll">SCROLL TO DISCOVER</div></section>
<section className="intro"><Heart size={22}/><p>“{c.greeting}”</p><span>Pengkhotbah 3:11</span></section>
<section className="couple" id="cerita"><div className="portrait"><img src={photo(c.coupleImage,"1000")} alt={`${c.groom} dan ${c.bride}`}/></div><div className="couple-copy"><p className="eyebrow dark">Mempelai</p><h2>{c.groom}<br/><i>&</i> {c.bride}</h2><p>{c.story}</p><div className="signature">J & C</div></div></section>
<section id="acara" className="event-section"><p className="eyebrow">Save the date</p><h2>Hari Bahagia Kami</h2><div className="event-card"><div className="calendar"><span>{d.toLocaleDateString("id-ID",{month:"short"})}</span><strong>{d.getDate()}</strong><em>{d.getFullYear()}</em></div><div className="event-details"><h3>Pemberkatan & Resepsi</h3><p><CalendarDays/> {fd} · {c.time}</p><p><MapPin/> {c.venue}<br/><small>{c.address}</small></p><a className="pill dark-pill" href={c.mapsUrl} target="_blank">Buka Google Maps</a></div></div><div className="map-wrap"><iframe title={`Peta ${c.venue}`} src={`https://www.google.com/maps?q=${encodeURIComponent(c.address)}&output=embed`} loading="lazy" referrerPolicy="no-referrer-when-downgrade"/></div></section>
<section id="galeri" className="gallery-section"><p className="eyebrow dark">Our moments</p><h2>Galeri Kasih</h2><div className="gallery-grid">{(c.gallery.length?c.gallery:["","",""]).slice(0,6).map((src,i)=><img key={i} src={photo(src,String(900+i))} alt={`Foto galeri ${i+1}`}/>)}</div></section>
<section id="hadiah" className="gift-section"><Gift/><p className="eyebrow">Tanda Kasih</p><h2>Hadiah Pernikahan</h2><p>Doa dan kehadiran Anda adalah hadiah terindah. Jika ingin memberikan tanda kasih:</p><div className="bank"><span>{c.bankName}</span><strong>{c.accountNumber}</strong><small>a.n. {c.accountHolder}</small></div></section>
<footer><Music2/><h2>{c.groom} <i>&</i> {c.bride}</h2><p>Terima kasih atas doa dan restu Anda.</p><a href="/admin">Admin</a></footer></main>}
